config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :posts do
   resources :reviews
  end
  
  root 'posts#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :posts

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	belongs_to :category
	has_many :reviews

	has_attached_file :post_image, styles: { large: "600x600", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :post_image, content_type: /\Aimage\/.*\Z/
	
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
 
  has_many :posts
  has_many :reviews

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


before_action :find_post, only: [:show, :edit, :update, :destroy]
#show/edit/update/destroy are the ACTIONS that require my find_post method
#because they require me to find the post id
#"posts/:id format -> for more information see the routes :)"


def index

	if params[:category].blank?
		@posts = Post.all.order("created_at DESC")
	else
		@category_id = Category.find_by(name: params[:category]).id
		@posts = Post.where(:category_id => @category_id).order("created_at DESC")
	end

end

def new
	@post = current_user.posts.build
	@categories = Category.all.map { |c| [c.name, c.id]}
end


def show 
	if @post.reviews.blank?
		@averageReview = 0
	else
		@averageReview = @post.reviews.average(:rating).round(2)
	end
end

def create
	@post = current_user.posts.build(post_params())
	@post.category_id = params[:category_id]

	if @post.save # This is a commit
		
		flash[:success] = "O seu anuncio foi criado com sucesso!"
		redirect_to root_path
	else
		render 'new'
	end

end


def edit
	@categories = Category.all.map { |c| [c.name, c.id]}
	
end

def update
	@post.category_id = params[:category_id]
	if @post.update(post_params())
		redirect_to post_path(@post)
	else
		render 'edit'
	end
end

def destroy
	@post.destroy
	redirect_to root_path
end

private
	def post_params()
		params.require(:post).permit(:title, :description, :autor, :category_id, :post_image)
	end

	def find_post()
		# This function will search for a specific
		# post and show it to the user
		@post = Post.find(params[:id])
	end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :find_post
	before_action :find_review, only: [:edit, :update, :destroy]

	def new	
		@review = Review.new
	end

	def create 
		@review = Review.new(review_params)

		@review.post_id = @post.id
		@review.user_id = current_user.id
		
		if @review.save #Commit 
			redirect_to post_path(@post)
		else
			render 'new'
		end

	end

	def destroy
		@review.destroy
		redirect_to post_path(@post)
	end

	def edit
	end

	def update
		@review = Review.find(params[:id])
		if @review.update(review_params)
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	private

		def review_params
			params.require(:review).permit(:rating, :comment)
		end


		def find_post	
			@post = Post.find(params[:post_id])
		end

		def find_review	
			@review = Review.find(params[:id])
		end


end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
 before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  

  <title>Teste</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  <!-- This is for the slider. I SHOULD REPLACE THIS FOR LOCAL LINKS -->
  <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.5.7/slick.min.js"></script>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.7/slick.css"/>

</head>
<body>


<nav class="navbar navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <!-- isto é uma erb tag e so funciona porque tenho a extençao .erb que me permite usar ruby em paginas html-->
      <%= link_to root_path, class: 'navbar-brand' do %>
          <i class="fa fa-terminal fa-inverse"></i>
          <strong style="color:#FFFFFF;">RoR APP</strong>
      <% end %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <div class="nav navbar-nav navbar-right" style="padding-right: 20px;">
        <% if current_user %>
          <%= link_to "Sign Out",destroy_user_session_path, method: :delete ,class: "btn btn-primary navbar-btn" %>
        <% else %>
          <%= link_to "Login",new_user_session_path, method: :get ,class: "btn btn-default navbar-btn" %>
          <%= link_to "Sign up",new_user_registration_path, method: :get ,class: "btn btn-primary navbar-btn" %>
        <% end %>

      </div>

    <div class="nav navbar-nav">
    	
		<li class="dropdown">
			<a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categorias <span class="caret"></span></a>

			<ul class="dropdown-menu" role="menu">
				<% Category.all.each do |category| %>
					<li class="<%= 'active' if params[:category] == category.name %>">
						<%= link_to category.name, root_path(category: category.name) %>
					</li>
				<% end %>

			</ul>

		</li>

       <ul class="nav navbar-nav">
				
		<% if user_signed_in? %>
			<li>
				<%= link_to "Novo Anuncio", new_post_path %>
			</li>
		<% end %>

	   </ul>
    </div>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



    
  <% flash.each do |key,value| %>
    
      <%= content_tag :div, value , class: "alert alert-#{key}" %>

  <% end %> 
	

	<div class="container">
	  <%= yield %>
 	</div>





  


</body>
</html>

app/views/posts/_form.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3 col-xs-6 col-xs-offset-3">
		<div class="well">

			<%= simple_form_for @post, :html => { :multipart => true} do |f| %>
				<%= select_tag(:category_id,options_for_select(@categories), :prompt => "Escolha a categoria: ")
				%>

				<%= f.file_field :post_image %>

				<%= f.input :title, label: "Job title:" %>
				<%= f.input :description %>
				<%= f.input :autor %>
				<%= f.button :submit, class: 'btn btn-primary btn-lg btn-block' %>
			<% end %>

		</div>
	</div>	
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<!-- :html => { :multipart => true} it's needed to use
the PaperClip gem that will allow us to upload images,etc -->

<%= simple_form_for @post, :html => { :multipart => true} do |f| %>
	<%= f.select :category_id, @categories
	%>
	<%= f.file_field :post_image %>
	<%= f.input :title, label: "Job title:" %>
	<%= f.input :description %>
	<%= f.input :autor %>
	<%= f.button :submit, class: 'btn btn-primary btn-lg btn-block' %>
<% end %>

app/views/posts/index.html.erb
<!-- START SLIDER -->

<div class="slider-container">

	<div class="homeSlider">
	  <div><img src="http://placehold.it/940x528"></div>
	  <div><img src="http://placehold.it/940x528"></div>
	  <div><img src="http://placehold.it/940x528"></div>
	</div>

</div>


<!-- END SLIDER -->
<div class="container">

	<div class="row" style="position:relative;margin-top:550px;">

		<h1><%= params[:category] %></h1>


		<% if @posts.count == 0 %>
			<h2>Não existem anuncios nesta categoria :(</h2>
		<% end %>

		<% @posts.each do |post| %>
			<div class="col-md-4">
				
				<a href="/posts/<%= post.id %>">
					<%= image_tag post.post_image.url, class: "post-image" %>
				</a>

			</div>
			
		<% end %>


	</div>

</div>

app/views/posts/new.html.erb
<h1 class="text-center">NEW POST</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="row">
	
	<div class="col-md-6">
		<h1> <%= @post.title %> </h1>
		<%=image_tag @post.post_image.url, class: "post-show"  %>

	</div>
	<div class="col-md-6" style="padding-top:50px;">
		
		<h3> Classificação </h3>
		<div class="average-rating" data-score="<%= @averageReview %>"></div>
		<span>(<%= @post.reviews.count %> reviews)</span>
		<h3> autor: <%= @post.autor %> </h3>
		<h3>categoria: <%= @post.category.name %></h3>
		<p> description: <%= @post.description %> </p>
	</div>
</div>

<div class="row">
	<div class="col-md-8">
		<!-- Place for the reviews -->

		<%= render @post.reviews %>

		<% if user_signed_in? %>
			<div>
			<%= link_to "Add Review", new_post_review_path(@post) %>
			</div>
		<% end %>

	</div>
</div>



<%= link_to "Voltar", root_path	 %>

<% if user_signed_in? %>

	<% if @post.user == current_user %>

		<%= link_to "Editar", edit_post_path(@post) %>

		<%= link_to "remover", post_path(@post), method: :delete, data: {confirm: "Deseja mesmo remover este anuncio?"} %>
	<% end %>
<% end %>


<script>

	$( document ).ready(function() {

		$(".review-rating").raty({
			readOnly: true,
			score: function () {
				return $(this).attr('data-score');
			},
			path: '/assets/'
		});




		$('.average-rating').raty({
			readOnly: true,
			path: '/assets/',
			score: function() {
				return $(this).attr('data-score')
			}
		});
	});

</script>

app/views/reviews/_form.html.erb
<%= simple_form_for([@post, @post.reviews.build]) do |f| %>
	
	<div id="rating-form">
		<label>Classificação: </label>
	</div>
	
	<%= f.input :comment %>

	<%= f.button :submit %>

<% end %>


<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review-rating" data-score="<%= review.rating %>"></div>

<p><%= review.comment %></p>


<% if user_signed_in? %>
	<% if review.user_id == current_user.id %>

		<%= link_to "Edit", edit_post_review_path(review.post, review) %>
		<%= link_to "Delete", post_review_path(review.post, review), method: :delete, data: {confirm: "Queres mesmo apagar?"} %>


	<% end %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= simple_form_for([@post, @review]) do |f| %>
	
	<div id="rating-form">
		<label>Classificação: </label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit %>

<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>